# Generated by Django 5.2.14 on 2026-05-19 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommonFields',
        ),
    ]
